services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: todo-frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
