// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type BuildingBlock = {
    id: number;
    name: string;
    dataType: string;
};

export type CategoryCreationDto = {
    user_id?: number;
    name?: string;
    buildingBlockIds?: Array<number>;
};

export type Category = {
    id?: number;
    name: string;
    userId?: number;
    buildingBlocks: Array<BuildingBlock>;
};

export type Void = {
    [key: string]: unknown;
};

export type LinkUpdateDto = {
    buildingBlockId?: number;
    dataValue?: string;
};

export type ToDoUpdateLinkDataDto = {
    buildingBlockData?: Array<LinkUpdateDto>;
};

export type ToDoBuildingBlockDataLinkId = {
    buildingBlockId?: number;
    todoId?: number;
};

export type ToDoBuildingBlockDataLink = {
    id?: ToDoBuildingBlockDataLinkId;
    buildingBlockId?: BuildingBlock;
    todo?: ToDo;
    dataValue?: string;
};

export type ToDo = {
    id?: number;
    categoryId?: Category;
    userId?: number;
    createdAt?: string;
    priority?: string;
    dueToday?: boolean;
    completed?: boolean;
    buildingBlockData?: Array<ToDoBuildingBlockDataLink>;
};

export type ToDoBuildingBlockDataDto = {
    buildingBlockId?: number;
    dataValue?: string;
};

export type ToDoCreationDto = {
    categoryId?: number;
    createdAt?: string;
    priority?: string;
    completed?: boolean;
    buildingBlockData?: Array<ToDoBuildingBlockDataDto>;
    dueToday?: boolean;
    user_id?: number;
};

export type GetAllBuildingBlocksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todoApp/buildingBlocks';
};

export type GetAllBuildingBlocksResponses = {
    /**
     * OK
     */
    200: Array<BuildingBlock>;
};

export type GetAllBuildingBlocksResponse = GetAllBuildingBlocksResponses[keyof GetAllBuildingBlocksResponses];

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todoApp/categories';
};

export type GetAllCategoriesResponses = {
    /**
     * OK
     */
    200: Array<Category>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type AddCategoryData = {
    body: CategoryCreationDto;
    path?: never;
    query?: never;
    url: '/todoApp/categories';
};

export type AddCategoryResponses = {
    /**
     * OK
     */
    200: Category;
};

export type AddCategoryResponse = AddCategoryResponses[keyof AddCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/todoApp/categories/{id}';
};

export type DeleteCategoryResponses = {
    /**
     * OK
     */
    200: Void;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type UpdateLinkDataData = {
    body: ToDoUpdateLinkDataDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/todoApp/todo/{id}/data';
};

export type UpdateLinkDataResponses = {
    /**
     * OK
     */
    200: ToDo;
};

export type UpdateLinkDataResponse = UpdateLinkDataResponses[keyof UpdateLinkDataResponses];

export type SetCompletedData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/todoApp/todo/{id}/complete';
};

export type SetCompletedResponses = {
    /**
     * OK
     */
    200: ToDo;
};

export type SetCompletedResponse = SetCompletedResponses[keyof SetCompletedResponses];

export type SetDueTodayData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/todoApp/todo/{id}/due-today';
};

export type SetDueTodayResponses = {
    /**
     * OK
     */
    200: ToDo;
};

export type SetDueTodayResponse = SetDueTodayResponses[keyof SetDueTodayResponses];

export type GetAllToDosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todoApp/todo';
};

export type GetAllToDosResponses = {
    /**
     * OK
     */
    200: Array<ToDo>;
};

export type GetAllToDosResponse = GetAllToDosResponses[keyof GetAllToDosResponses];

export type CreateToDoData = {
    body: ToDoCreationDto;
    path?: never;
    query?: never;
    url: '/todoApp/todo';
};

export type CreateToDoResponses = {
    /**
     * OK
     */
    200: ToDo;
};

export type CreateToDoResponse = CreateToDoResponses[keyof CreateToDoResponses];

export type DeleteToDoData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/todoApp/todo/{id}';
};

export type DeleteToDoResponses = {
    /**
     * OK
     */
    200: Void;
};

export type DeleteToDoResponse = DeleteToDoResponses[keyof DeleteToDoResponses];
